onlyBuiltDependencies:
  - '@homebridge/node-pty-prebuilt-multiarch'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - msgpackr-extract
  - sharp
  - workerd
